language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE palettepicker_test;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: af4cdtoT+mvOCZq8Y5crwtHgk6cUTtPp914h4cMkVdiwgD6qcH2yqvz2RyX9zMwYrJnX/jWbXfrdA0SenQfwkESJOuYPyQe4ea6lWeDQWUcUxzYwGrg//3yaOrtFvE6E/xI4oXPo4pyiIVWvsUG7wCJwq8/SZUNT4wjBkyDLPEgrhSzr0lXbHKCbq6CYzofAAzlNtUc7xaIXbjsCpwC6mjF1bL+JvNzP+FvNNSfMH3FiBaWUDcQSRrBss79V+xN0+1losBLI+mCfDpIEN8reBqOKXnjVG13JqKHb7hh5YlF8AwZ6IUQNuXfxSBHzgxqe4mT1WjrsAEpG6PaXU27v0B9w0LFHQOpCuBDuT3j0NucFMcyQSTpaCqhMbPGULjjqZN8vbJb7mPbMKYDbV9tzqlZmUqeySN9J3dcUsbmBWPQQ57Q26K7/GaotEYSfo2MkoXEqrelKtNN18qty7c9t/AxgxpRQghaAPWpv9OAaj2zzpi01e4+7QD8cjNuztJbfCkjCBQcstyfjjDY1DVCaHfJxV+x2W2SvBNcAf8teHIuSpuhOpKcOcueOiBFAcsMhTvtl974i0W1R7uYWyzfhkbja4pGqi52jC2zRj236NGAcf7Md0mNP5LNOQbCfoUrQimAC9B8hvnAx1ccoTgXZ6Cz7aRR8A/x3wEDYH3gkQPo=
  app: allthecolorsofthewind
  skip_cleanup: true
